### ISSUE TITLE
How to upload and download files in object storage using this library

### ISSUE THREAD

**Issue by gowridev** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#1]
How to upload and download files in object storage using this library. 

I am referring to below functionalities given below

http://developer.openstack.org/api-ref-objectstorage-v1.html#createOrReplaceObject (to ulpoad files using openstack API)
http://developer.openstack.org/api-ref-objectstorage-v1.html#showObject (to download files using openstack API)

**Comment by dgonz7** [comment]
Hi, how is this different from what is explained in the readme: https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#create-a-new-object-or-update-an-existing-one ?

**Comment by gowridev** [comment]
Thanks for your response. I was unable to relate Object section in Openstack API with ObjectStorageContainer section of this module. Good example will help us to understand the functions like how to give file as input parameters to upload function & download function.  Could you please help integrating this code with parse-server as file adapter?
