### ISSUE TITLE
Is there a way to stream data to Bluemix Object Storage?

### ISSUE THREAD

**Issue by rnchamberlain** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#13]
I am copying a file to Object Storage, using the bluemix-objectstorage API like this:

```
  objectStorage = new ObjectStorage(credentials);

  objectStorage.getContainer(myContainer)
    .then(function(container) {
	....
        fs.readFile(filename, (err, data) => {
          ....
          container.createObject(filename, data)
```
This is loading the whole file into the `data` variable before passing it to the` container.createObject()` call. Is there a way to stream the file direct to a new Object Storage object instead? Thanks!

**Comment by abaruni** [comment]
@rnchamberlain unfortunately there are not streaming APIs available from the Object Storage service so it is not possible to stream a file directly to a new Object Storage object

**Comment by rnchamberlain** [comment]
OK, thanks for the quick response, closing this now.
