### ISSUE TITLE
Publish deprecation release

### ISSUE THREAD

**Issue by glennrfisher** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#14]
I was asked to deprecate this repository and provided administrative access to do so. I updated the repository description and readme.

Unfortunately, I do not have permission to publish a new release to npm. Could you please run the following command to deprecate this project:

```bash
npm deprecate bluemix-objectstorage "This package has been deprecated and is no longer actively maintained."
```

**Comment by abaruni** [comment]
done

**Comment by glennrfisher** [comment]
Thanks!

**Comment by alokrajiv** [comment]
Hi Guys, Is there an alternative SDK at the moment? Came to this repo straight from the docs link in my bluemix console.
