### ISSUE TITLE
how to use cosbench with bluemix object store

### ISSUE THREAD

**Issue by gowridev** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#2]
Could you please guide me how to use [cosbench](https://github.com/intel-cloud/cosbench) with bluemix object store? Are there any other tools for load testing of object storage?

**Comment by dgonz7** [comment]
Hi, 

I think that for benchmarking you just work directly with the REST API; you can read more here: https://new-console.ng.bluemix.net/docs/services/ObjectStorage/index.html
