### ISSUE TITLE
How to integrate this library with parse server fileadapter

### ISSUE THREAD

**Issue by gowridev** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#3]
I would like to integrate parse server with this library. Could you please guide me regarding this. 
I am referring to configuring [parse file Adapters](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-file-adapters)

**Comment by gowridev** [comment]
I asked same question in parse server [question link](https://github.com/ParsePlatform/parse-server/issues/2007) . They suggested to write a custom file adapter(FilesAdapter.js). I would like to know can integrate this library with  [parse fileadapter.js](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Files/FilesAdapter.js) . This feature will help many people who want host parse in bluemix.

**Comment by abaruni** [comment]
@gowridev no, this library is solely for consuming the standard Object Storage service offering on bluemix
