### ISSUE TITLE
Simply doing a list of containers

### ISSUE THREAD

**Issue by enkidoo** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#4]
## Below are my code:

`require('dotenv').config();`

`var ObjectStorage = require('bluemix-objectstorage').ObjectStorage;`

`var credentials = {`
`projectId: process.env.PROJECT_ID,`
`userId: process.env.USER_ID,`
`password: process.env.PASSWORD,`
`region: ObjectStorage.Region.DALLAS`
`};`

`var objStorage = new ObjectStorage(credentials);`

`objStorage.listContainers()`
`.then(function(containerList) {`
`console.log(containerList)`
`// containerList - an array of ObjectStorageContainers`
`// containerList may be empty`
`})`
`.catch(function(err) {`
`console.log(err);`
`// AuthTokenError if there was a problem refreshing authentication token`
`// ServerError if any unexpected status codes were returned from the request`
`});`

I got the following error, originating from your source code.

/home/ubuntu/workspace/swift_storage/node_modules/bluemix-objectstorage/lib/HttpClient.js:51
    this.authToken.expiration = body.token.expires_at;

**Comment by abaruni** [comment]
@enkidoo my apologies for not responding. i wasn't being notified of activity. are you still having an issue here?

**Comment by harishvarma8055** [comment]
@abaruni @enkidoo Iam facing the same issue..Can you please let me know how to resolve this
